---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_

:release_build:
 :output: PICLib
 :use_assembly: FALSE
 :artifacts:
    - build/release/Build.hex

:environment:

:extension:
  :executable: .out
  :subproject: .a         #This is only here at the moment because of define erros in release_invoker
  :subprojects: .a

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/src/**
  :support:
    - test/support
  :include:
    - "/opt/microchip/xc16/v1.26/support/dsPIC33E/h/"
    - "/opt/microchip/xc16/v1.26/support/generic/h/"
    - src/headers/**

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines
    - __dsPIC33EP128GP502__
    - UNITY_INT_WIDTH=16
    - UNITY_POINTER_WIDTH=16
    - CMOCK_MEM_INDEX_TYPE=uint16_t
    - CMOCK_MEM_PTR_AS_INT=uint16_t
    - CMOCK_MEM_ALIGN=1
    - CMOCK_MEM_SIZE=4096
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
  :release:
    - *common_defines
  :release_preprocess:
    - *common_defines


:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:tools:
  :test_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=33EP128GP502
      - -c
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wall
      #- -Werror  # We can't keep this on during test becuase of a CMock pointer issue
      - -O0
      - -mno-eds-warn
      - -omf=elf
      - -DXPRJ_default=default
      - -msmart-io=1
      - -msfr-warn=off
      - -legacy-libc
  :test_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=33EP128GP502
      - ${1}
      - -o "./build/test/TestBuild.out"
      - -omf=elf
      - -DXPRJ_default=default
      - -legacy-libc
      - -Wl,--local-stack,--defsym=__MPLAB_BUILD=1,--script=p33EP128GP502.gld,--stack=16,--check-sections,--data-init,--pack-data,--handles,--isr,--no-gc-sections,--fill-upper=0,--stackguard=16,--no-force-link,--smart-io,-Map="./build/test/TestOutput.map"
  :test_fixture:
    :executable: ruby
    :name: "Microchip simulator test fixture"
    :stderr_redirect: :auto #inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/simulation/sim_test_fixture.rb

  :release_compiler:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=33EP128GP502
      - -c
      - "${1}"
      - -o "${2}"
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -Wall
      #- -Werror  # We can't keep this on during test becuase of a CMock pointer issue
      - -O0
      - -mno-eds-warn
      - -g
      - -omf=elf
      - -DXPRJ_default=default
      - -msmart-io=1
      - -msfr-warn=off
      - -legacy-libc
      - -msfr-warn=off
  :release_linker:
    :executable: xc16-gcc
    :arguments:
      - -mcpu=33EP128GP502
      - ${1}
      - -o "./build/release/Build.hex"
      - -omf=elf
      - -DXPRJ_default=default
      - -legacy-libc
      -  -Wl,--local-stack,--defsym=__MPLAB_BUILD=1,--script=p33EP128GP502.gld,--stack=16,--check-sections,--data-init,--pack-data,--handles,--isr,--no-gc-sections,--fill-upper=0,--stackguard=16,--no-force-link,--smart-io,-Map="./build/artifacts/release/Releasr.map",--report-mem
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
